#!/usr/bin/env python3
"""Generate Ada's Android vector drawables from the one geometry.

Three families come out of it: the coloured Ada for the session card
(ada_stage_N / ada_frost_N), her flat status-bar mask (ic_stat_ada_N /
ic_stat_frost_N), and the Quick Settings tile icon (ic_qs_ada).

She exists three times over — a Flutter CustomPainter, a SwiftUI Shape, and
these — and three hand-drawn mascots drift within two releases. So the Android
copies are not drawn: they are emitted from the same interpolation the painter
uses, with the same coefficients, in the same 60x60 space.

    lib/shared/mascot/ada_mascot.dart   (the source of truth)
    ios/AmbientWidgets/AdaShape.swift   (the same maths, in Swift)

Run after changing any of those:

    python3 tool/generate_ada_android.py
"""
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'android', 'app', 'src', 'main', 'res', 'drawable')

STAGES = 5  # kMeltStages

# Melting, then frost — the two states of matter, never blended.
MELT = {'body': '#CBBCFD', 'stroke': '#5A44F1', 'ink': '#31237C'}
FROST = {'body': '#D7EEF8', 'stroke': '#9FD6EF', 'ink': '#3F6D84'}


def body_path(m: float) -> str:
    """The cube, sagging into a puddle. Identical maths to the painter."""
    tY, bY = 8 + 15 * m, 50 + 2 * m
    tL, tR = 11 + 7 * m, 49 - 7 * m
    bL, bR = 11 - 6 * m, 49 + 6 * m
    rTop, rBot = 9 + 3 * m, 9 + 13 * m
    sag = 2.5 * m
    return (
        f"M{tL + rTop:.2f},{tY:.2f} "
        f"L{tR - rTop:.2f},{tY:.2f} "
        f"Q{tR:.2f},{tY:.2f} {tR:.2f},{tY + rTop:.2f} "
        f"L{bR:.2f},{bY - rBot:.2f} "
        f"Q{bR:.2f},{bY:.2f} {bR - rBot:.2f},{bY:.2f} "
        f"Q30.00,{bY + sag:.2f} {bL + rBot:.2f},{bY:.2f} "
        f"Q{bL:.2f},{bY:.2f} {bL:.2f},{bY - rBot:.2f} "
        f"L{tL:.2f},{tY + rTop:.2f} "
        f"Q{tL:.2f},{tY:.2f} {tL + rTop:.2f},{tY:.2f} Z"
    )


def face_paths(m: float, frozen: bool) -> str:
    """Melting she is happy — closed, curved eyes and a smile. Frozen she is
    merely held: open dots and a level mouth. Ada is never sad about a pause."""
    tY, bY = 8 + 15 * m, 50 + 2 * m
    cy = (tY + bY) / 2 + 1
    eyeY = cy - 2
    r = 2.7 - 0.5 * m
    dx = 6 - 1.2 * m
    mY = cy + 4.6
    ink = (FROST if frozen else MELT)['ink']
    w = 1.7
    out = []

    if frozen:
        for sx in (-1, 1):
            x = 30 + sx * dx
            out.append(
                f'    <path android:fillColor="{ink}" android:pathData='
                f'"M{x - r * 0.85:.2f},{eyeY:.2f} a{r * 0.85:.2f},{r * 0.85:.2f} 0 1,0 '
                f'{r * 1.7:.2f},0 a{r * 0.85:.2f},{r * 0.85:.2f} 0 1,0 -{r * 1.7:.2f},0 Z" />'
            )
        out.append(
            f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
            f'android:strokeLineCap="round" android:pathData='
            f'"M{30 - 4.4:.2f},{mY:.2f} L{30 + 4.4:.2f},{mY:.2f}" />'
        )
    else:
        for sx in (-1, 1):
            x = 30 + sx * dx
            out.append(
                f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
                f'android:strokeLineCap="round" android:pathData='
                f'"M{x - r:.2f},{eyeY:.2f} Q{x:.2f},{eyeY - r * 1.9:.2f} {x + r:.2f},{eyeY:.2f}" />'
            )
        out.append(
            f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
            f'android:strokeLineCap="round" android:pathData='
            f'"M{30 - 4.4:.2f},{mY:.2f} Q30.00,{mY + 3.6:.2f} {30 + 4.4:.2f},{mY:.2f}" />'
        )
    return "\n".join(out)


def drawable(m: float, frozen: bool) -> str:
    tone = FROST if frozen else MELT
    stroke_w = 3.4 - 1.2 * m
    spurs = ""
    if frozen:
        # At 24dp these, not the hue, are what say "held" — a status bar mask
        # takes every colour away.
        pairs = [(30, 2.5, 30, 10), (30, 50, 30, 57.5), (2.5, 30, 10, 30),
                 (50, 30, 57.5, 30), (10, 10, 15.5, 15.5), (50, 10, 44.5, 15.5),
                 (10, 50, 15.5, 44.5), (50, 50, 44.5, 44.5)]
        spurs = "\n".join(
            f'    <path android:strokeColor="{tone["stroke"]}" android:strokeWidth="1.6" '
            f'android:strokeLineCap="round" android:pathData="M{a},{b} L{c},{d}" />'
            for a, b, c, d in pairs
        )
    gloss = ""
    if m < 0.8:
        fade = 1 - 0.55 * m
        tY = 8 + 15 * m
        gloss = (
            f'    <path android:fillColor="#FFFFFF" android:fillAlpha="{0.85 * fade:.2f}" '
            f'android:pathData="M17.9,{tY + 6:.2f} a2.1,2.1 0 1,0 4.2,0 a2.1,2.1 0 1,0 -4.2,0 Z" />'
        )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/generate_ada_android.py — do not edit by hand.
     Ada at melt {m:.2f}{", frozen" if frozen else ""}. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="60"
    android:viewportHeight="60">
    <path
        android:fillColor="{tone['body']}"
        android:strokeColor="{tone['stroke']}"
        android:strokeWidth="{stroke_w:.2f}"
        android:pathData="{body_path(m)}" />
{gloss}
{spurs}
{face_paths(m, frozen)}
</vector>
'''


# The mask's canvas. Ada's 60x60 space leaves a wide margin the painter needs
# for her shadow; at 24dp in a status bar that margin is wasted pixels, so the
# masks crop to the 56 units she and her frost spurs actually occupy.
MASK_VIEWPORT = 56
MASK_INSET = 2


def mask(m: float, frozen: bool) -> str:
    """Ada for the status bar: one flat colour, no fill, no stroke, no face.

    Android masks a status-bar icon to a single colour, so everything that
    tells a melting Ada from a frozen one has to survive as outline alone
    (spec §4, and "the constraint that will bite" in §6). Melting, that is the
    sag of the silhouette. Frozen, it is the spurs — and because a spur drawn
    over the body disappears in a mask, the body steps back to let them show.
    """
    stroke_w = 3.4 - 1.2 * m
    body = (
        f'<path android:fillColor="#FFFFFFFF" android:strokeColor="#FFFFFFFF" '
        f'android:strokeWidth="{stroke_w:.2f}" android:strokeLineJoin="round" '
        f'android:pathData="{body_path(m)}" />'
    )
    if frozen:
        pairs = [(30, 2.5, 30, 10), (30, 50, 30, 57.5), (2.5, 30, 10, 30),
                 (50, 30, 57.5, 30), (10, 10, 15.5, 15.5), (50, 10, 44.5, 15.5),
                 (10, 50, 15.5, 44.5), (50, 50, 44.5, 44.5)]
        spurs = "\n".join(
            f'        <path android:strokeColor="#FFFFFFFF" android:strokeWidth="2.6" '
            f'android:strokeLineCap="round" android:pathData="M{a},{b} L{c},{d}" />'
            for a, b, c, d in pairs
        )
        inner = (
            f'        <group android:pivotX="30" android:pivotY="29" '
            f'android:scaleX="0.8" android:scaleY="0.8">\n'
            f'            {body}\n'
            f'        </group>\n{spurs}'
        )
    else:
        inner = f'        {body}'
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/generate_ada_android.py — do not edit by hand.
     Ada's status-bar mask at melt {m:.2f}{", frozen" if frozen else ""}: one flat colour. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{MASK_VIEWPORT}"
    android:viewportHeight="{MASK_VIEWPORT}">
    <group android:translateX="-{MASK_INSET}" android:translateY="-{MASK_INSET}">
{inner}
    </group>
</vector>
'''


def tile_icon() -> str:
    """Ada for the Quick Settings tile (spec §7).

    A tile icon is tinted to one colour like a status-bar icon, but it is drawn
    large enough to keep a face — so here she is the whole cube, with the
    closed eyes, the smile and the gloss cut out of it rather than drawn on.
    """
    g = 1.7  # half her outline, folded into the fill so the silhouette matches
    tL, tR, tY, bY, r = 11 - g, 49 + g, 8 - g, 50 + g, 9 + g
    cube = (
        f"M{tL + r:.2f},{tY:.2f} L{tR - r:.2f},{tY:.2f} "
        f"Q{tR:.2f},{tY:.2f} {tR:.2f},{tY + r:.2f} L{tR:.2f},{bY - r:.2f} "
        f"Q{tR:.2f},{bY:.2f} {tR - r:.2f},{bY:.2f} L{tL + r:.2f},{bY:.2f} "
        f"Q{tL:.2f},{bY:.2f} {tL:.2f},{bY - r:.2f} L{tL:.2f},{tY + r:.2f} "
        f"Q{tL:.2f},{tY:.2f} {tL + r:.2f},{tY:.2f} Z"
    )
    t = 2.4  # how thick a cut has to be to survive at 24dp

    def band(x0: float, y0: float, cx: float, cy: float, x1: float, y1: float) -> str:
        """A stroked quadratic, as the outline a mask can cut out.

        A vector drawable cannot subtract a stroke, only a filled shape, so the
        painter's eye and mouth strokes are walked and offset by half their
        width to either side.
        """
        steps = 12
        left, right = [], []
        for i in range(steps + 1):
            u = i / steps
            x = (1 - u) ** 2 * x0 + 2 * (1 - u) * u * cx + u ** 2 * x1
            yy = (1 - u) ** 2 * y0 + 2 * (1 - u) * u * cy + u ** 2 * y1
            dx = 2 * (1 - u) * (cx - x0) + 2 * u * (x1 - cx)
            dy = 2 * (1 - u) * (cy - y0) + 2 * u * (y1 - cy)
            n = (dx * dx + dy * dy) ** 0.5
            nx, ny = -dy / n * t / 2, dx / n * t / 2
            left.append((x + nx, yy + ny))
            right.append((x - nx, yy - ny))
        pts = left + right[::-1]
        return "M" + " L".join(f"{a:.2f},{b:.2f}" for a, b in pts) + " Z"

    def eye(cx: float) -> str:
        # The painter's closed, happy eye — a touch wider so it survives 24dp.
        y, er = 28.2, 3.1
        return band(cx - er, y, cx, y - er * 1.9, cx + er, y)

    smile = band(30 - 4.8, 34.2, 30, 34.2 + 4.0, 30 + 4.8, 34.2)
    gloss = "M17.90,14.00 a2.1,2.1 0 1,0 4.2,0 a2.1,2.1 0 1,0 -4.2,0 Z"
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/generate_ada_android.py — do not edit by hand.
     Ada for the Quick Settings tile: the cube, her face cut out of it. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{MASK_VIEWPORT}"
    android:viewportHeight="{MASK_VIEWPORT}">
    <group android:translateX="-{MASK_INSET}" android:translateY="-{MASK_INSET}">
        <path
            android:fillColor="#FFFFFFFF"
            android:fillType="evenOdd"
            android:pathData="{cube} {eye(24)} {eye(36)} {smile} {gloss}" />
    </group>
</vector>
'''


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    written = []

    def write(name: str, body: str) -> None:
        with open(os.path.join(OUT, name), 'w') as fh:
            fh.write(body)
        written.append(name)

    for stage in range(STAGES):
        m = stage / (STAGES - 1)
        write(f'ada_stage_{stage}.xml', drawable(m, frozen=False))
        write(f'ada_frost_{stage}.xml', drawable(m, frozen=True))
        write(f'ic_stat_ada_{stage}.xml', mask(m, frozen=False))
        write(f'ic_stat_frost_{stage}.xml', mask(m, frozen=True))
    write('ic_qs_ada.xml', tile_icon())
    print(f"wrote {len(written)} drawables to res/drawable/")


if __name__ == '__main__':
    main()
