#!/usr/bin/env python3
"""Generate Ada's Android vector drawables from the one geometry.

She exists three times over — a Flutter CustomPainter, a SwiftUI Shape, and
these — and three hand-drawn mascots drift within two releases. So the Android
copies are not drawn: they are emitted from the same interpolation the painter
uses, with the same coefficients, in the same 60x60 space.

    lib/shared/mascot/ada_mascot.dart   (the source of truth)
    ios/AmbientWidgets/AdaShape.swift   (the same maths, in Swift)

Run after changing any of those:

    python3 tool/generate_ada_android.py
"""
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'android', 'app', 'src', 'main', 'res', 'drawable')

STAGES = 5  # kMeltStages

# Melting, then frost — the two states of matter, never blended.
MELT = {'body': '#CBBCFD', 'stroke': '#5A44F1', 'ink': '#31237C'}
FROST = {'body': '#D7EEF8', 'stroke': '#9FD6EF', 'ink': '#3F6D84'}


def body_path(m: float) -> str:
    """The cube, sagging into a puddle. Identical maths to the painter."""
    tY, bY = 8 + 15 * m, 50 + 2 * m
    tL, tR = 11 + 7 * m, 49 - 7 * m
    bL, bR = 11 - 6 * m, 49 + 6 * m
    rTop, rBot = 9 + 3 * m, 9 + 13 * m
    sag = 2.5 * m
    return (
        f"M{tL + rTop:.2f},{tY:.2f} "
        f"L{tR - rTop:.2f},{tY:.2f} "
        f"Q{tR:.2f},{tY:.2f} {tR:.2f},{tY + rTop:.2f} "
        f"L{bR:.2f},{bY - rBot:.2f} "
        f"Q{bR:.2f},{bY:.2f} {bR - rBot:.2f},{bY:.2f} "
        f"Q30.00,{bY + sag:.2f} {bL + rBot:.2f},{bY:.2f} "
        f"Q{bL:.2f},{bY:.2f} {bL:.2f},{bY - rBot:.2f} "
        f"L{tL:.2f},{tY + rTop:.2f} "
        f"Q{tL:.2f},{tY:.2f} {tL + rTop:.2f},{tY:.2f} Z"
    )


def face_paths(m: float, frozen: bool) -> str:
    """Melting she is happy — closed, curved eyes and a smile. Frozen she is
    merely held: open dots and a level mouth. Ada is never sad about a pause."""
    tY, bY = 8 + 15 * m, 50 + 2 * m
    cy = (tY + bY) / 2 + 1
    eyeY = cy - 2
    r = 2.7 - 0.5 * m
    dx = 6 - 1.2 * m
    mY = cy + 4.6
    ink = (FROST if frozen else MELT)['ink']
    w = 1.7
    out = []

    if frozen:
        for sx in (-1, 1):
            x = 30 + sx * dx
            out.append(
                f'    <path android:fillColor="{ink}" android:pathData='
                f'"M{x - r * 0.85:.2f},{eyeY:.2f} a{r * 0.85:.2f},{r * 0.85:.2f} 0 1,0 '
                f'{r * 1.7:.2f},0 a{r * 0.85:.2f},{r * 0.85:.2f} 0 1,0 -{r * 1.7:.2f},0 Z" />'
            )
        out.append(
            f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
            f'android:strokeLineCap="round" android:pathData='
            f'"M{30 - 4.4:.2f},{mY:.2f} L{30 + 4.4:.2f},{mY:.2f}" />'
        )
    else:
        for sx in (-1, 1):
            x = 30 + sx * dx
            out.append(
                f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
                f'android:strokeLineCap="round" android:pathData='
                f'"M{x - r:.2f},{eyeY:.2f} Q{x:.2f},{eyeY - r * 1.9:.2f} {x + r:.2f},{eyeY:.2f}" />'
            )
        out.append(
            f'    <path android:strokeColor="{ink}" android:strokeWidth="{w}" '
            f'android:strokeLineCap="round" android:pathData='
            f'"M{30 - 4.4:.2f},{mY:.2f} Q30.00,{mY + 3.6:.2f} {30 + 4.4:.2f},{mY:.2f}" />'
        )
    return "\n".join(out)


def drawable(m: float, frozen: bool) -> str:
    tone = FROST if frozen else MELT
    stroke_w = 3.4 - 1.2 * m
    spurs = ""
    if frozen:
        # At 24dp these, not the hue, are what say "held" — a status bar mask
        # takes every colour away.
        pairs = [(30, 2.5, 30, 10), (30, 50, 30, 57.5), (2.5, 30, 10, 30),
                 (50, 30, 57.5, 30), (10, 10, 15.5, 15.5), (50, 10, 44.5, 15.5),
                 (10, 50, 15.5, 44.5), (50, 50, 44.5, 44.5)]
        spurs = "\n".join(
            f'    <path android:strokeColor="{tone["stroke"]}" android:strokeWidth="1.6" '
            f'android:strokeLineCap="round" android:pathData="M{a},{b} L{c},{d}" />'
            for a, b, c, d in pairs
        )
    gloss = ""
    if m < 0.8:
        fade = 1 - 0.55 * m
        tY = 8 + 15 * m
        gloss = (
            f'    <path android:fillColor="#FFFFFF" android:fillAlpha="{0.85 * fade:.2f}" '
            f'android:pathData="M17.9,{tY + 6:.2f} a2.1,2.1 0 1,0 4.2,0 a2.1,2.1 0 1,0 -4.2,0 Z" />'
        )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/generate_ada_android.py — do not edit by hand.
     Ada at melt {m:.2f}{", frozen" if frozen else ""}. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="60"
    android:viewportHeight="60">
    <path
        android:fillColor="{tone['body']}"
        android:strokeColor="{tone['stroke']}"
        android:strokeWidth="{stroke_w:.2f}"
        android:pathData="{body_path(m)}" />
{gloss}
{spurs}
{face_paths(m, frozen)}
</vector>
'''


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    written = []
    for stage in range(STAGES):
        m = stage / (STAGES - 1)
        path = os.path.join(OUT, f'ada_stage_{stage}.xml')
        with open(path, 'w') as fh:
            fh.write(drawable(m, frozen=False))
        written.append(os.path.basename(path))
    for stage in range(STAGES):
        m = stage / (STAGES - 1)
        path = os.path.join(OUT, f'ada_frost_{stage}.xml')
        with open(path, 'w') as fh:
            fh.write(drawable(m, frozen=True))
        written.append(os.path.basename(path))
    print(f"wrote {len(written)} drawables to res/drawable/")


if __name__ == '__main__':
    main()
